// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadMysqlTrace returns the embedded CollectionSpec for mysqlTrace.
func loadMysqlTrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MysqlTraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load mysqlTrace: %w", err)
	}

	return spec, err
}

// loadMysqlTraceObjects loads mysqlTrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*mysqlTraceObjects
//	*mysqlTracePrograms
//	*mysqlTraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadMysqlTraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadMysqlTrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// mysqlTraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type mysqlTraceSpecs struct {
	mysqlTraceProgramSpecs
	mysqlTraceMapSpecs
	mysqlTraceVariableSpecs
}

// mysqlTraceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type mysqlTraceProgramSpecs struct {
	HandleExecve *ebpf.ProgramSpec `ebpf:"handle_execve"`
}

// mysqlTraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type mysqlTraceMapSpecs struct {
}

// mysqlTraceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type mysqlTraceVariableSpecs struct {
}

// mysqlTraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadMysqlTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type mysqlTraceObjects struct {
	mysqlTracePrograms
	mysqlTraceMaps
	mysqlTraceVariables
}

func (o *mysqlTraceObjects) Close() error {
	return _MysqlTraceClose(
		&o.mysqlTracePrograms,
		&o.mysqlTraceMaps,
	)
}

// mysqlTraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadMysqlTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type mysqlTraceMaps struct {
}

func (m *mysqlTraceMaps) Close() error {
	return _MysqlTraceClose()
}

// mysqlTraceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadMysqlTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type mysqlTraceVariables struct {
}

// mysqlTracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadMysqlTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type mysqlTracePrograms struct {
	HandleExecve *ebpf.Program `ebpf:"handle_execve"`
}

func (p *mysqlTracePrograms) Close() error {
	return _MysqlTraceClose(
		p.HandleExecve,
	)
}

func _MysqlTraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed mysqltrace_bpfeb_gobpf.o
var _MysqlTraceBytes []byte
